name: moviebuff
description: "MovieBuff — movie ticket booking app (MAD II)."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.0
  flutter_svg: ^2.2.3
  provider: ^6.1.5+1
  carousel_slider: ^5.1.1
  http: ^1.6.0
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.1

  # MAD II additions
  sqflite: ^2.4.1
  path: ^1.9.0
  path_provider: ^2.1.5
  connectivity_plus: ^6.1.0
  geolocator: ^13.0.2
  image_picker: ^1.1.2
  battery_plus: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/logo.png
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: assets/images/logo.png
  adaptive_icon_foreground_inset: 18
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/data/external_movies.json
    - assets/data/offline_catalog.json
